version: "3.8"
services:
    db:
        image: mariadb
        container_name: db_${APP_NAME}
        restart: always
        volumes:
            - dev:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT}
            MYSQL_DATABASE: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PWD}
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_${APP_NAME}
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
    www:
        build: php
        container_name: www_${APP_NAME}
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www
        restart: always
    # Uncomment to use Directus
    # directus:
    #     container_name: directus-${APP_NAME}
    #     image: directus/directus:9.0.0-rc.99
    #     ports:
    #         - "8055:8055"
    #     volumes:
    #         - ./directus/uploads:/directus/uploads
    #         - ./directus/extensions:/directus/extensions
    #     depends_on:
    #         - db
    #     environment:
    #         KEY: 'f0330228-9a78-4c27-9e87-fc5f9b49574d'
    #         SECRET: 'CcnMDO7Olvoaqpi83cAoFlpYXb6FIsoS'
    #         DB_CLIENT: 'mysql'
    #         DB_HOST: 'db'
    #         DB_PORT: '3306'
    #         DB_DATABASE: ${DATABASE_NAME}
    #         DB_USER: 'root'
    #         DB_PASSWORD: ${DATABASE_PWD}

volumes:
    dev:
